services:
  db:
    container_name: db
    image: postgres:alpine3.20
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - db


volumes:
  db-data: