services:
  db:
    container_name: db
    image: postgres:alpine3.20
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    environment:
      - PORT=3000
      - JWT_SECRET=your_secret_key
      - DATABASE_URL=postgres://postgres:postgres@db:5432/db
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "8080:8080"



volumes:
  db-data: